# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/00_pipeline.ipynb (unless otherwise specified).

__all__ = ['pl_logger', 'load_trained_model', 'coord_sparsity_and_manifold', 'ModelTrainer', 'CFGeneratorBase',
           'LocalCFGenerator', 'is_predictive_model', 'GlobalCFGenerator', 'Evaluator', 'Experiment']

# Cell
from .import_essentials import *
from .utils import *
from .training_module import BaseModule, CFNetTrainingModule
from .model import BaselinePredictiveModel, CounterNetModel
from .base_interface import LocalExplainerBase, GlobalExplainerBase, ExplainerBase
from .cf_explainer import VanillaCF
from .evaluation import SensitivityMetric, proximity
from sklearn.neighbors import NearestNeighbors

logging.getLogger('pytorch_lightning').setLevel(logging.ERROR)
pl_logger = logging.getLogger("pytorch_lightning.core")

# Cell
def load_trained_model(module: BaseModule, checkpoint_path: str, gpus: int = 0) -> BaseModule:
    """
    Load weights from a Lightning checkpoint into a constructed module.
    """
    checkpoint_path = str(checkpoint_path)
    if not os.path.exists(checkpoint_path):
        raise FileNotFoundError(f"{checkpoint_path} is not found.")

    if gpus > 0 and torch.cuda.is_available():
        device = torch.device("cuda")
    else:
        device = torch.device("cpu")

    # Load checkpoint
    ckpt = torch.load(checkpoint_path, map_location=device)
    state_dict = ckpt.get("state_dict", ckpt)

    # Load weights into the provided module
    try:
        module.load_state_dict(state_dict)
    except RuntimeError:
        module.load_state_dict(state_dict, strict=False)

    module.to(device)
    module.eval()
    return module


def coord_sparsity_and_manifold(pred_model: BaseModule,
                                x: torch.Tensor,
                                cf: torch.Tensor,
                                target_y: Optional[torch.Tensor] = None,
                                ref_model: Optional[BaseModule] = None,
                                eps: float = 0.05,
                                n_neighbors: int = 1) -> tuple[float, float]:
    """
    Sparsity + manifold distance.

    Sparsity:
        1 - E[#(|cf - x| > eps) / d]

    Manifold distance:
        For each CF, compute L1 distance to the nearest neighbor among the
        training set restricted to label == target_y.
    """
    # Clamp to [0, 1]
    x_clamped = x.clamp(0.0, 1.0)
    cf_clamped = cf.clamp(0.0, 1.0)

    # ---- Sparsity ----
    delta = (cf_clamped - x_clamped).abs()
    changed_mask = delta > eps
    changed_per_sample = changed_mask.sum(dim=1)
    d = x_clamped.size(-1)
    sparsity = 1.0 - (changed_per_sample / float(d)).mean().item()

    # ---- Reference training set ----
    ref = ref_model if ref_model is not None else pred_model
    train_x, train_y = ref.train_dataset[:]
    train_x_clamped = train_x.clamp(0.0, 1.0)

    train_np = train_x_clamped.detach().cpu().numpy()
    train_y_np = train_y.detach().view(-1).cpu().numpy().astype(int)
    cf_np = cf_clamped.detach().cpu().numpy()

    target_np = target_y.detach().view(-1).cpu().numpy().astype(int)
    if cf_np.shape[0] != target_np.shape[0]:
        raise ValueError(f"target_y has length {target_np.shape[0]} but cf has {cf_np.shape[0]} samples")

    # Compute per-target-class NN distances
    dists_out = np.full((cf_np.shape[0],), np.nan, dtype=np.float32)
    for t in np.unique(target_np):
        cf_idx = np.where(target_np == t)[0]
        if cf_idx.size == 0:
            continue

        train_idx = np.where(train_y_np == t)[0]
        if train_idx.size == 0:
            continue

        k_eff = min(int(n_neighbors), int(train_idx.size))
        nn = NearestNeighbors(n_neighbors=k_eff, metric="manhattan")
        nn.fit(train_np[train_idx])
        dists, _ = nn.kneighbors(cf_np[cf_idx])
        dists_out[cf_idx] = dists[:, -1]  # kth-NN within target class

    manifold_dist = float(np.nanmean(dists_out)) if not np.all(np.isnan(dists_out)) else float('nan')
    return sparsity, manifold_dist


def _to_feature_space(pred_model: BaseModule, X: torch.Tensor) -> torch.Tensor:
    """
    Map from the model's coordinate space (continuous + one-hot categoricals)
    to a feature-level space: [cont_1, ..., cont_C, disc_1, ..., disc_D]
    """
    # continuous then categorical part
    cat_idx = pred_model.cat_normalizer.cat_idx
    categories = pred_model.cat_normalizer.categories

    # split continuous and categorical coordinates
    X_cont = X[:, :cat_idx]
    if not categories:
        return X_cont

    X_cat = X[:, cat_idx:]

    feat_parts = [X_cont]

    start = 0
    for cats in categories:
        k = len(cats)
        if k == 0:
            continue

        seg = X_cat[:, start:start + k]
        idx = seg.argmax(dim=1)

        if k > 1:
            val = idx.float() / float(k - 1) # [0, 1]
        else:
            val = torch.zeros_like(idx, dtype=torch.float)

        feat_parts.append(val.unsqueeze(-1))
        start += k

    return torch.cat(feat_parts, dim=1) # (n_samples, C + D)


# Cell
class ModelTrainer(object):
    def __init__(self,
                 model: BaseModule,
                 t_configs: Dict[str, Any],
                 callbacks: Optional[List[Callback]] = None,
                 description: Optional[str] = None,
                 debug: Optional[bool] = False,
                 logger: Optional[Union[LightningLoggerBase, bool]] = None,
                 logger_name: str = "debug"):

        if logger is None:
            logger = pl_loggers.TensorBoardLogger(
                save_dir="log/",
                name=logger_name,
                log_graph=False,
                default_hp_metric=False,
            )


        # model checkpoint
        self.checkpoint_callback = ModelCheckpoint(
            monitor='val/val_loss', save_top_k=3, mode='min'
        )

        # define callbacks
        if callbacks is None:
            callbacks = [self.checkpoint_callback]
        elif self._has_no_model_checkpoint(callbacks):
            callbacks += [self.checkpoint_callback]

        self.trainer = pl.Trainer(logger=logger, callbacks=callbacks, **t_configs)

        self.model = model

    def _has_no_model_checkpoint(self, callbacks: List[Callback]) -> bool:
        for callback in callbacks:
            if isinstance(callback, ModelCheckpoint):
                return False
        return True

    def fit(self, is_parallel=False):
        if is_parallel:
            logging.warning(
                f"parallel version has not been implemented\nUsing the single process training...")
        self.trainer.fit(self.model)

        return self.model

    def save_best_model(self, dir_path: Path):
        if not dir_path.is_dir():
            raise ValueError(f"'{dir_path}' is not a directory")

        best_model_path = Path(self.checkpoint_callback.best_model_path)
        if not best_model_path.is_file():
            raise FileNotFoundError(f"Best model checkpoint not found at {best_model_path}")

        dest_path = dir_path / best_model_path.name
        shutil.copy(best_model_path, dest_path)

        # create an alias 'best.ckpt'
        alias_path = dir_path / "best.ckpt"
        shutil.copy(dest_path, alias_path)

        return dest_path

    def load_trained_model(self, checkpoint_path: str, gpus: int = 0) -> BaseModule:
        self.model = load_trained_model(
            self.model, checkpoint_path=checkpoint_path, gpus=gpus)
        return self.model

# Cell
class CFGeneratorBase(ABC):
    results = {
        "x": None,
        "cf": None,
        "y": None,
        "y_hat": None,
        "cf_y": None,
        "cf_y_hat": None,
        "sensitivity": None,
        "total_time": None,
        "avg_time": None,
        "cf_algo": None,
        "cat_idx": None,
        "manifold_dist": None,
        "sparsity": None,
    }

    def __init__(self, cf_algo: ExplainerBase,
                 pred_model: BaselinePredictiveModel,
                 configs: Dict[str, Any] = {}, ref_model:
                Optional[BaselinePredictiveModel] = None):
        self.configs = configs
        self.pred_model = pred_model
        self.ref_model = ref_model if ref_model is not None else pred_model
        self.pred_model.freeze()

        self.cf_algo = cf_algo
        self.results.update({"cf_algo": type(cf_algo).__name__})
        self.dataset = pred_model.test_dataset
        self.sensitivity = pred_model.sensitivity

    def generate(self, dataset: Optional[TensorDataset]=None, test_size: Optional[int] = None, debug: bool = False):
        raise NotImplementedError

# Cell
class LocalCFGenerator(CFGeneratorBase):
    def __init__(self, cf_algo: LocalExplainerBase,
        pred_model: BaselinePredictiveModel,
        configs: Dict[str, Any] = {},
        ref_model: Optional[BaselinePredictiveModel] = None):
        super().__init__(cf_algo, pred_model, configs, ref_model=ref_model)
        # define cf_algo
        if not issubclass(type(cf_algo), LocalExplainerBase):
            raise ValueError(f"cf_algo should be an instance of `{LocalExplainerBase}`, but got `{type(cf_algo)}`. ")
        CFExplainer = type(cf_algo)
        pred_fn = pred_model.forward
        cat_normalizer = pred_model.cat_normalizer
        self.cf_algo = CFExplainer(pred_fn, cat_normalizer, configs)

        self.is_parallel = configs['is_parallel'] if 'is_parallel' in configs else True

    def gen_step(self, x):
        x = x.reshape(1, -1)
        cf = self.cf_algo.generate_cf(x)
        return x, cf

    def iterative_generate(self, size: int, dataset: TensorDataset):
        result = []
        start_time = time.time()
        for ix, (x, y) in enumerate(tqdm(dataset)):
            if ix < size:
                x, cf = self.gen_step(x)
                result.append((x, cf))
        total_time = time.time() - start_time
        avg_time = total_time / size
        return result, {'total_time': total_time, 'avg_time': avg_time}

    def __unpack_x_cf(self, result: List[torch.Tensor]):
        X = torch.rand((len(result), result[0][0].size(-1)))
        cf_algo = X.clone()

        for ix, (x, cf) in enumerate(result):
            X[ix, :] = x
            cf_algo[ix, :] = cf
        return X, cf_algo

    def generate(self, dataset: Optional[TensorDataset] = None, test_size: Optional[int] = None, debug: bool = False):
        if dataset is None:
            dataset = self.pred_model.test_dataset
        if test_size is None:
            size = len(dataset) if not debug else 3
        else:
            size = test_size

        result = []

        if self.is_parallel and not debug:
            print(f"generating {size} cfs in parallel...")
            result = Parallel(n_jobs=-1, max_nbytes=None, verbose=False)(
                delayed(self.gen_step) (x=x)
                for ix, (x, y) in enumerate(tqdm(dataset)) if ix < size
            )
            print(f"evaluating speed by generating 50 cfs...")
            _, time = self.iterative_generate(50, dataset)
        else:
            print(f"generating {size} cfs...")
            result, time = self.iterative_generate(size, dataset)

        self.results.update(time)

        x, cf = self.__unpack_x_cf(result)
        _, y = dataset[:]
        y = y[:size]
        y_hat = self.pred_model.predict(x)
        cf_y_hat = self.pred_model.predict(cf)

        sensitivity = self.pred_model.sensitivity
        sensitivity.reset()

        if self.configs.get("cf_target_filter") == "flip_neg_stay_pos":
            cf_y = torch.ones_like(y_hat)
        else:
            cf_y = flip_binary(y_hat)

        self.results.update({
            'x': x,
            'cf': cf,
            'y': y,
            'y_hat': y_hat,
            'cf_y': cf_y,
            'cf_y_hat': cf_y_hat,
        })
        self.results.update({'sensitivity': sensitivity(x, cf, cf_y).item()})

        eps = self.configs.get('sparsity_eps', 0.05)
        k = self.configs.get('manifold_k', 1)
        neg_mask = (y_hat == 0).reshape(-1)

        if neg_mask.sum() > 0:
            sparsity_val, man_dist = coord_sparsity_and_manifold(
                self.pred_model,
                x[neg_mask],
                cf[neg_mask],
                target_y=cf_y[neg_mask],
                ref_model=self.ref_model,
                eps=eps, n_neighbors=k
            )
        else:
            sparsity_val, man_dist = float('nan'), float('nan')

        self.results.update({
            'sparsity': sparsity_val,
            'manifold_dist': man_dist,
        })

        return self.results

# Cell
# a temp workaround
def is_predictive_model(model: BaseModule):
    return callable(getattr(model, "predict", None))

# Cell
class GlobalCFGenerator(CFGeneratorBase):
    def __init__(self, cf_algo: GlobalExplainerBase,
            pred_model: Optional[BaselinePredictiveModel] = None, configs: Dict[str, Any] = {},
                 ref_model: Optional[BaselinePredictiveModel] = None) -> None:
        if not issubclass(type(cf_algo), GlobalExplainerBase):
            raise ValueError(f"cf_algo should be an instance of `{GlobalCFGenerator}`, but got `{type(cf_algo)}`")
        if not is_predictive_model(cf_algo) and pred_model is None:
            raise ValueError(f"pred_model should be passed when cf_algo is {type(cf_algo)}.")
        if is_predictive_model(cf_algo):
            pred_model = cf_algo
        super().__init__(cf_algo, pred_model, configs, ref_model=ref_model)

    def generate(self, dataset: Optional[TensorDataset]=None, test_size: Optional[int] = None, debug: bool = False):
        if dataset is None:
            dataset = self.pred_model.test_dataset
        if test_size is None:
            size = len(dataset) if not debug else 3
        else:
            size = test_size
        x, y = dataset[:]

        print(f"generating {len(dataset)} cfs...")
        cf = self.cf_algo.generate_cf(x)

        print(f"evaluating speed...")
        start_time = time.time()
        for i, (sample, _) in enumerate(dataset):
            if i < size:
                self.cf_algo.generate_cf(sample.reshape(1, -1))
        total_time = time.time() - start_time
        avg_time = total_time / size

        y_hat = self.pred_model.predict(x)
        cf_y_hat = self.pred_model.predict(cf)

        sensitivity = self.pred_model.sensitivity
        sensitivity.reset()

        if self.configs.get("cf_target_filter") == "flip_neg_stay_pos":
            cf_y = torch.ones_like(y_hat)
        else:
            cf_y = flip_binary(y_hat)

        self.results.update({
            'x': x,
            'cf': cf,
            'y': y,
            'y_hat': y_hat,
            'cf_y': cf_y,
            'cf_y_hat': cf_y_hat,
        })
        self.results.update({'sensitivity': sensitivity(x, cf, cf_y).item()})
        self.results.update({'total_time': total_time, 'avg_time': avg_time})

        eps = self.configs.get('sparsity_eps', 0.05)
        k = self.configs.get('manifold_k', 1)

        neg_mask = (y_hat == 0).reshape(-1) # evaluate only on negatives

        if neg_mask.sum() > 0:
            sparsity_val, man_dist = coord_sparsity_and_manifold(
                self.pred_model,
                x[neg_mask],
                cf[neg_mask],
                target_y=cf_y[neg_mask],
                ref_model=self.ref_model,
                eps=eps, n_neighbors=k
            )
        else:
            sparsity_val, man_dist = float('nan'), float('nan')

        self.results.update({
            'sparsity': sparsity_val,
            'manifold_dist': man_dist,
        })

        return self.results

# Cell
class Evaluator(object):
    def __init__(self, configs: Dict[str, Any]={}):
        self.is_logging: bool = configs.get('is_logging', True)

    def eval(self, results: Dict[str, Any], dir_path: Path):
        if not dir_path.exists():
            raise ValueError(f"{dir_path} does not exist.")
        csv_path = dir_path / Path('metrics.csv')

        metrics = [
            'cat_proximity',
            'cont_proximity',
            #'validity',
            'sensitivity',
            'time',
            'pred_accuracy',
            'proximity',
            'sparsity',
            'manifold_dist',
            'validity_recourse', # fraction of y_hat==0 that reach class 1
            'stability_pos', # fraction of y_hat==1 that stay class 1
            #'validity_goal_pos',  # y_hat==0 reach 1, y_hat==1 stay 1
        ]
        # ['diffs', 'total_num']

        if csv_path.exists():
            r = pd.read_csv(csv_path, index_col=0).to_dict()
            for metric in metrics:
                if metric not in r.keys():
                    r[metric] = dict()
        else:
            r = {metric:{} for metric in metrics}

        x, cf, y, y_hat, cf_y, cf_y_hat = (
            results['x'],
            results['cf'],
            results['y'],
            results['y_hat'],
            results['cf_y'],
            results['cf_y_hat'],
        )
        cat_idx, cf_name = results['cat_idx'], results['cf_algo']

        # --- Proximity ---
        neg_mask = (y_hat == 0).reshape(-1)

        if neg_mask.sum() > 0:
            x_prox = x[neg_mask]
            cf_prox = cf[neg_mask]
        else:
            x_prox = x
            cf_prox = cf
            print(f"[WARN] No negative predictions found for {cf_name}. Proximity computed on entire set.")

        cont_prox = proximity(x_prox[:, :cat_idx], cf_prox[:, :cat_idx]).item()
        cat_prox = proximity(x_prox[:, cat_idx:], cf_prox[:, cat_idx:]).item()
        r['cont_proximity'][cf_name] = cont_prox
        r['cat_proximity'][cf_name] = cat_prox

        # divide by number of features
        n_features = x.size(-1)
        r['proximity'][cf_name] = (cont_prox + cat_prox) / float(n_features)

        # other metrics
        #r['validity'][cf_name] = accuracy(cf_y.int(), cf_y_hat.int()).item()
        r['sensitivity'][cf_name] = results['sensitivity']
        r['time'][cf_name] = results['avg_time']
        r['pred_accuracy'][cf_name] = accuracy(y.int(), y_hat.int()).item()

        # sparsity + manifold distance
        r['sparsity'][cf_name] = float(results['sparsity'])
        r['manifold_dist'][cf_name] = float(results['manifold_dist'])

        # do CFs reach the positive class for those predicted as negative
        neg_mask = (y_hat == 0)
        if neg_mask.any():
            target_pos = torch.ones_like(cf_y_hat[neg_mask])
            r['validity_recourse'][cf_name] = accuracy(target_pos.int(), cf_y_hat[neg_mask].int()).item()
        else:
            r['validity_recourse'][cf_name] = float('nan')

        # do CFs stay in the positive class for predicted positives
        pos_mask = (y_hat == 1)
        if pos_mask.any():
            target_pos = torch.ones_like(cf_y_hat[pos_mask])
            r['stability_pos'][cf_name] = accuracy(target_pos.int(), cf_y_hat[pos_mask].int()).item()
        else:
            r['stability_pos'][cf_name] = float('nan')

        #target_all_pos = torch.ones_like(cf_y_hat)
        #r['validity_goal_pos'][cf_name] = accuracy(target_all_pos.int(), cf_y_hat.int()).item()

        final_result_df = pd.DataFrame.from_dict(r)
        print(tabulate(final_result_df.astype("float16"), headers = 'keys', tablefmt = 'pretty'))
        if self.is_logging:
            final_result_df.to_csv(csv_path)
            torch.save(results, dir_path / f"{cf_name}_results.pt")
            print("Results have been saved!")
        return final_result_df

# Cell
class Experiment(object):
    def __init__(self, explainers: List[ExplainerBase],
            m_configs: List[Dict[str, Any]], t_configs: Optional[Dict[str, Any]] = None, debug: bool = False):
        self.explainers = explainers
        self.m_configs = m_configs
        self.use_pred_model = False # need a `BaselinePredictiveModel` or not
        self.pred_model = None      # init a `BaselinePredictiveModel` if neccesary
        if t_configs is None:
            self.t_configs = load_configs(Path('assets/configs/trainer.json'))
        else:
            self.t_configs = t_configs
        self.__check_explainers()
        self.debug = debug

        self.evaluator = Evaluator(configs={'is_logging': True})

    def __is_type(self, instance):
        return isinstance(type(instance), type) or isinstance(type(instance), ABCMeta)

    def __check_explainers(self):
        for explainer in self.explainers: # explainer is already passed as a type
            if self.__is_type(explainer):
                explainer_type = deepcopy(explainer)
                # explainer = explainer_type(self.m_configs[0])
            else:
                explainer_type = type(explainer)
            if not issubclass(explainer_type, ExplainerBase):
                raise ValueError(f"The explainer should be a subclass of `{ExplainerBase}`, but got `{explainer_type}`")
            if not (isinstance(explainer, CounterNetModel) or (issubclass(explainer_type, CFNetTrainingModule))):
                self.use_pred_model = True

    def __check_seeds(self, seeds: Optional[List[int]]):
        if seeds is not None and len(seeds) > 0:
            return list(seeds)

        env_seed = os.environ.get("PL_GLOBAL_SEED")
        if env_seed is not None:
            try:
                return [int(env_seed)]
            except ValueError:
                pass

        default_seed = 31
        print(f"[INFO] No seed provided; defaulting to {default_seed}")
        return [default_seed]

    def __make_dir(self, dataset_name: str, seed: int):
        dir_path = Path(f'assets/results/{dataset_name}/seed-{seed}/')
        dir_path.mkdir(parents=True, exist_ok=True)
        return dir_path

    def explainer_step(self, explainer: ExplainerBase, pred_model: BaselinePredictiveModel,
            m_config: Dict[str, Any], dir_path: Path):
        if not self.__is_type(explainer):
            CFExplainer = type(explainer)
        else:
            CFExplainer = explainer
        if issubclass(CFExplainer, GlobalExplainerBase):
            if issubclass(CFExplainer, CounterNetModel):
                model = CFExplainer(m_config)
            else:
                model = CFExplainer(m_config, pred_model)

            # train CounterNet
            logger_name = f"{CFExplainer.__name__.lower()}/{m_config['dataset_name']}"
            cfnet_trainer = ModelTrainer(model, self.t_configs, logger_name=logger_name)
            cfnet_trainer.fit()

            # Save best checkpoint
            best_model_path = cfnet_trainer.save_best_model(dir_path)

            # Reload the best checkpoint before generating CFs
            try:
                model = cfnet_trainer.load_trained_model(
                    checkpoint_path=str(best_model_path),
                    gpus=0,
                )
            except Exception as e:
                pl_logger.warning(
                    f"[WARN] Failed to reload best checkpoint from {best_model_path}: {e}"
                )

            cf_generator = GlobalCFGenerator(model, configs=m_config, ref_model=pred_model)

        else:
            print(f"Generating local explanation for {CFExplainer}")
            local_cfg = dict(m_config)
            if CFExplainer is VanillaCF:
                local_cfg.pop("cf_target_filter", None)
            cf_generator = LocalCFGenerator(
                CFExplainer(pred_model.predict),
                pred_model,
                configs=local_cfg,
                ref_model=pred_model
            )
        results = cf_generator.generate(debug=self.debug)
        self.evaluator.eval(results, dir_path)

    def experiment_step(self, m_config, seed: int):
        # train a baseline predictive model
        if self.use_pred_model:
            print("training predictive model...")
            pred_model_trainer = ModelTrainer(
                BaselinePredictiveModel(m_config), self.t_configs, logger_name="pred_model")
            pred_model = pred_model_trainer.fit()
        else:
            pred_model = None

        dataset_name = m_config['dataset_name']
        # logging dir
        dir_path = self.__make_dir(dataset_name, seed)

        for explainer in self.explainers:
            self.explainer_step(explainer, pred_model, m_config, dir_path)

    def run(self, seeds: Optional[List[int]] = None):
        seeds = self.__check_seeds(seeds)
        for seed in seeds:
            seed_everything(seed, workers=True)
            for m_config in self.m_configs:
                self.experiment_step(m_config, seed)